name: publish

on:
  push:
    branches:
      - main
      - next
      - beta
      - alpha

permissions:
  contents: read

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Set Up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install Project Dependencies
        run: bun install

      - name: Build the package
        run: bun run build

      - name: Create Distribution Archive
        run: |
          zip -r build.zip dist package.json CHANGELOG.md README.md LICENSE
          tar -czvf build.tar.gz dist package.json CHANGELOG.md README.md LICENSE

      - name: Publish Package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
          GITHUB_NPM_CONFIG_REGISTRY: https://npm.pkg.github.com/
          GITHUB_NPM_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
          PUBLIC_NPM_CONFIG_REGISTRY: https://registry.npmjs.org
          PUBLIC_NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

        run: bun run release
